[workspace]
members = [
    "pkg/boot",
    "pkg/elf",
    "pkg/fs",
    "pkg/kernel",
    "pkg/lib",
    "pkg/app/sh",
    "pkg/app/hello",
    "pkg/app/ttt"
]

[profile.release-with-debug]
inherits = "release"
debug = true
