[workspace]
members = [
    "pkg/boot",
    "pkg/elf",
    "pkg/fs",
    "pkg/kernel",
    "pkg/lib",
    "pkg/app/*"
]
exclude = ["pkg/app/config", "pkg/app/.cargo"]

[profile.release-with-debug]
inherits = "release"
debug = true
