[package]
name = "ggos_kernel"
version = "0.6.4"
edition = "2021"
authors = ["GZTime <Time.GZ@outlook.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boot = { path = "../boot", package = "ggos_boot",  default-features = false }
fs = { path = "../fs", package = "ggfs" }
embedded-graphics = { version = "0.7.1", features = ['fixed_point'] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
paste = "1.0.7"
spin = "0.9.3"
x86 = "0.47.0"
x86_64 = "0.14.9"
log = "0.4.16"
bit_field = "0.10.1"
micromath = { version = "2.0.0", features = ["num-traits"] }
bitflags = "1.3.2"
chrono = { version = "0.4.19", default-features = false }
libm = "0.2.2"
linked_list_allocator = "0.9.1"
pc-keyboard = "0.5.1"
crossbeam-queue = { version = "0.3.5", default-features = false, features = ["alloc"] }
volatile = "0.4.4"
