[package]
name = "ggos_kernel"
version = "0.1.0"
edition = "2021"
authors = ["GZTime <gz.time.walker@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = { version = "0.7.1", features = ['fixed_point'] }
boot = { path = "../boot", package = "ggos_boot" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
paste = "1.0.7"
spin = "0.9.2"
x86 = "0.47.0"
x86_64 = "0.14.8"
log = "0.4.16"
bit_field = "0.10.1"
micromath = { version = "2.0.0", features = ["num-traits"] }
bitflags = "1.3.2"
chrono = { version = "0.4.19", default-features = false }
libm = "0.2.2"
