[package]
name = "ggos_kernel"
version = "0.1.0"
edition = "2021"
authors = ["GZTime <gz.time.walker@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = { version = "0.7.1", features = ['fixed_point'] }
boot = { path = "../boot", package = "ggos_boot" }
paste = "1.0.7"
spin = "0.9.2"
x86_64 = "0.14.8"
