[package]
name = "ggos_elf"
version = "0.1.0"
edition = "2021"
authors = ["GZTime <gz.time.walker@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.16"
x86_64 = "0.14.8"
xmas-elf  = "0.8"
