[package]
name = "ggos_elf"
edition.workspace = true
version.workspace = true
authors.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
x86_64 = "0.15"
xmas-elf = "0.9"
