[package]
name = "ggos_boot"
version = "0.1.0"
edition = "2021"
authors = ["GZTime <Time.GZ@outlook.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
uefi = "0.18.0"
uefi-services = { version = "0.15.0", optional = true}
log = "0.4.17"
x86_64 = "0.14.10"
xmas-elf = "0.9"
elf = { package = "ggos_elf", path = "../elf" }

[features]
boot = ["uefi/alloc", "uefi-services"]
default = ["boot"]
